# Generated by Django 5.0 on 2023-12-09 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bancos',
            new_name='Banco',
        ),
        migrations.RenameModel(
            old_name='Condominios',
            new_name='Condominio',
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos', models.CharField(max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('condominio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condominios.condominio')),
            ],
        ),
        migrations.DeleteModel(
            name='Gastos',
        ),
    ]
