# Generated by Django 5.0 on 2023-12-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0003_condominio_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gasto',
            old_name='gastos',
            new_name='gasto',
        ),
    ]
